#------------------------------------------------------------------------------
# VARIABLES
#------------------------------------------------------------------------------
# Variables specified in this file can be used in the documentation via:
#     {{ site.CONFIG_KEY }}
#------------------------------------------------------------------------------


# Download urls
download_url: ""
download_url_hadoop1: "" 
download_url_hadoop2: "" 

# Some commonly linked pages (this was more important to have as a variable
# during incubator; by now it should also be fine to hardcode these.)
website_url: "http://zuowang.github.io"
jira_url: "http://github.com/zuowang/zuowang.github.io/issues"
github_url: "http://github.com/zuowang/zuowang.github.io"

defaults:
  -
    scope:
      path: ""
    values:
      layout: plain

markdown: kramdown
highlighter: pygments

kramdown:
    toc_levels: 1..3

host: localhost

baseurl: 
